### ISSUE TITLE
Add license or permission notice to reproduce this text

### ISSUE THREAD

**Issue by tarcisioe** [jcelerier/cpp-teaching-manifesto#1]
Hi! I really like the contents of your manifesto, and I do agree with it entirely. So much that I, along with a group of other C++ programmers from Brazil, am using it as a guideline for contributions to a knowledge-base repository in Portuguese for teaching material for C++ (https://github.com/cppbrasil/material-de-aprendizado). We list quite a bit of material in English, but we'd like to add as much material in Portuguese as possible. I am currently linking to your repository, but would like to reproduce your manifesto in Portuguese (with credits, of course), but your repository has no license or notice that I could do such a thing. Therefore, I'd like to ask for your direct permission or (even better), for you to license this work under something as one of the Creative Commons licenses.

Thanks in advance and congratulations on your manifesto again, it sums up good C++ teaching very well!

**Comment by jcelerier** [comment]
hey ! ahaha that's super cool :) going to add a license, most likely CC0

**Comment by jcelerier** [comment]
da. have fun ! and if you can link the translation if you get around to doing it, I'll link it in the readme

**Comment by tarcisioe** [comment]
https://github.com/cppbrasil/material-de-aprendizado/blob/master/manifesto-de-ensino-em-cpp.md translation done by @patrickelectric and reviewed (and nitpicked, surely) by me! Thanks!

**Comment by jcelerier** [comment]
thanks, added the link :-)
